[package]
org = "healthcare"
name = "health.fhir.r4.uscore311.allergyintolerance"
version = "1.0.0"
distribution = "2201.10.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "AllergyIntolerance", "r4", "health.fhir.r4.uscore311"]
template = true
