[package]
org = "healthcare"
name = "health.fhir.r4.uscore311.specimen"
version = "1.0.0"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Specimen", "r4", "health.fhir.r4.uscore311"]
template = true
