[package]
org = "healthcare"
name = "health.fhir.r4.uscore311.medication"
version = "1.0.0"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Medication", "r4", "health.fhir.r4.uscore311"]
template = true
